-- =====================================================================
-- AGENDEI - banco multiestabelecimento (PostgreSQL)
-- Equivalente de banco.sql, que continua sendo o arquivo oficial do
-- MySQL/MariaDB. Os dois esquemas sao mantidos lado a lado: o mesmo
-- codigo PHP roda nos dois bancos.
--
-- Nao ha CREATE DATABASE nem USE: no PostgreSQL o banco ja existe e a
-- conexao ja aponta para ele.
--
-- Diferencas de dialeto aplicadas aqui:
--   AUTO_INCREMENT       -> GENERATED BY DEFAULT AS IDENTITY
--   ENUM                 -> VARCHAR + CHECK ... IN (...)
--   DATETIME             -> TIMESTAMP
--   TINYINT(1)           -> SMALLINT (o PHP le e grava 0/1, nao booleano)
--   KEY dentro da tabela -> CREATE INDEX depois do CREATE TABLE
--   ON UPDATE CURRENT_TIMESTAMP -> removido (nao existe no PostgreSQL)
-- =====================================================================

-- ---------------------------------------------------------------------
-- LIMPEZA
-- Ordem inversa das dependencias; CASCADE cobre o que sobrar.
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS avaliacoes CASCADE;
DROP TABLE IF EXISTS cliente_pacotes CASCADE;
DROP TABLE IF EXISTS pacotes CASCADE;
DROP TABLE IF EXISTS fidelidade_movimentos CASCADE;
DROP TABLE IF EXISTS pagamentos CASCADE;
DROP TABLE IF EXISTS notificacoes CASCADE;
DROP TABLE IF EXISTS lista_espera CASCADE;
DROP TABLE IF EXISTS configuracoes CASCADE;
DROP TABLE IF EXISTS tentativas_acesso CASCADE;
DROP TABLE IF EXISTS estabelecimento_plano CASCADE;
DROP TABLE IF EXISTS planos CASCADE;
DROP TABLE IF EXISTS logs_master CASCADE;
DROP TABLE IF EXISTS logs_autenticacao CASCADE;
DROP TABLE IF EXISTS agendamentos CASCADE;
DROP TABLE IF EXISTS bloqueios_agenda CASCADE;
DROP TABLE IF EXISTS horarios_profissionais CASCADE;
DROP TABLE IF EXISTS profissional_servico CASCADE;
DROP TABLE IF EXISTS servicos CASCADE;
DROP TABLE IF EXISTS administradores CASCADE;
DROP TABLE IF EXISTS profissionais CASCADE;
DROP TABLE IF EXISTS clientes CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS administradores_master CASCADE;
DROP TABLE IF EXISTS estabelecimento CASCADE;

-- ---------------------------------------------------------------------
-- ESTABELECIMENTOS
-- Uma linha por empresa. O slug identifica seu link publico e a
-- identidade visual fica nesta tabela.
-- ---------------------------------------------------------------------
CREATE TABLE estabelecimento (
  id_estabelecimento    INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nome                  VARCHAR(120) NOT NULL,
  slogan                VARCHAR(180) DEFAULT NULL,
  descricao             TEXT DEFAULT NULL,
  telefone              VARCHAR(20) DEFAULT NULL,
  whatsapp              VARCHAR(20) DEFAULT NULL,
  email                 VARCHAR(150) DEFAULT NULL,
  endereco              VARCHAR(180) DEFAULT NULL,
  bairro                VARCHAR(100) DEFAULT NULL,
  cidade                VARCHAR(100) DEFAULT NULL,
  uf                    VARCHAR(2) DEFAULT NULL,
  cep                   VARCHAR(9) DEFAULT NULL,
  horario_funcionamento TEXT DEFAULT NULL,
  instagram             VARCHAR(120) DEFAULT NULL,
  facebook              VARCHAR(120) DEFAULT NULL,
  data_atualizacao      TIMESTAMP DEFAULT NULL,
  slug                  VARCHAR(80) NOT NULL,
  cor_primaria          VARCHAR(7) NOT NULL DEFAULT '#1F4E5F',
  cor_secundaria        VARCHAR(7) NOT NULL DEFAULT '#5FAF8B',
  cor_fundo             VARCHAR(7) NOT NULL DEFAULT '#F5F1EA',
  fonte                 VARCHAR(30) NOT NULL DEFAULT 'padrao',
  logo                  TEXT DEFAULT NULL,
  status                VARCHAR(7) NOT NULL DEFAULT 'ativo',
  CONSTRAINT pk_estabelecimento PRIMARY KEY (id_estabelecimento),
  CONSTRAINT uk_estabelecimento_slug UNIQUE (slug),
  CONSTRAINT ck_estabelecimento_status CHECK (status IN ('ativo','inativo'))
);

-- ---------------------------------------------------------------------
-- ADMINISTRADORES MASTER
-- Contas globais, sem vinculo com uma empresa. A senha inicial e criada
-- pelo instalador PHP.
-- ---------------------------------------------------------------------
CREATE TABLE administradores_master (
  id_master        INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nome             VARCHAR(120) NOT NULL,
  email            VARCHAR(150) NOT NULL,
  senha_hash       VARCHAR(255) NOT NULL,
  status           VARCHAR(7) NOT NULL DEFAULT 'ativo',
  cor_primaria     VARCHAR(7) NOT NULL DEFAULT '#252B36',
  cor_secundaria   VARCHAR(7) NOT NULL DEFAULT '#6E8BFF',
  cor_fundo        VARCHAR(7) NOT NULL DEFAULT '#F3F5F8',
  fonte            VARCHAR(30) NOT NULL DEFAULT 'padrao',
  logo             TEXT DEFAULT NULL,
  totp_segredo         VARCHAR(255) DEFAULT NULL,
  totp_ativado_em      TIMESTAMP DEFAULT NULL,
  totp_ultimo_contador BIGINT DEFAULT NULL,
  ultimo_acesso    TIMESTAMP DEFAULT NULL,
  data_criacao     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP DEFAULT NULL,
  CONSTRAINT pk_administradores_master PRIMARY KEY (id_master),
  CONSTRAINT uk_master_email UNIQUE (email),
  CONSTRAINT ck_master_status CHECK (status IN ('ativo','inativo'))
);

-- ---------------------------------------------------------------------
-- USUARIOS DOS ESTABELECIMENTOS
-- Toda conta local pertence obrigatoriamente a uma empresa. O e-mail e unico
-- em toda a plataforma, pois identifica a pessoa na entrada geral e no Google.
-- Nas colunas opcionais o CHECK aceita NULL: em SQL, NULL IN (...) nao
-- viola a restricao.
-- ---------------------------------------------------------------------
CREATE TABLE usuarios (
  id_usuario         INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nome               VARCHAR(120) NOT NULL,
  email              VARCHAR(150) NOT NULL,
  senha_hash         VARCHAR(255) NOT NULL,
  telefone           VARCHAR(20) DEFAULT NULL,
  telefone_fixo      VARCHAR(20) DEFAULT NULL,
  login              VARCHAR(6) DEFAULT NULL,
  sexo               VARCHAR(1) DEFAULT NULL,
  nome_materno       VARCHAR(120) DEFAULT NULL,
  data_nascimento    DATE DEFAULT NULL,
  cep                VARCHAR(8) DEFAULT NULL,
  logradouro         VARCHAR(150) DEFAULT NULL,
  numero             VARCHAR(20) DEFAULT NULL,
  complemento        VARCHAR(60) DEFAULT NULL,
  bairro             VARCHAR(100) DEFAULT NULL,
  cidade             VARCHAR(100) DEFAULT NULL,
  uf                 VARCHAR(2) DEFAULT NULL,
  tipo               VARCHAR(12) NOT NULL DEFAULT 'cliente',
  status             VARCHAR(7) NOT NULL DEFAULT 'ativo',
  totp_segredo         VARCHAR(255) DEFAULT NULL,
  totp_ativado_em      TIMESTAMP DEFAULT NULL,
  totp_ultimo_contador BIGINT DEFAULT NULL,
  token_recuperacao  VARCHAR(64) DEFAULT NULL,
  token_expiracao    TIMESTAMP DEFAULT NULL,
  ultimo_acesso      TIMESTAMP DEFAULT NULL,
  data_criacao       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao   TIMESTAMP DEFAULT NULL,
  id_estabelecimento INTEGER NOT NULL,
  CONSTRAINT pk_usuarios PRIMARY KEY (id_usuario),
  CONSTRAINT uk_usuarios_registro UNIQUE (id_estabelecimento, id_usuario),
  CONSTRAINT uk_usuarios_email UNIQUE (email),
  CONSTRAINT uk_estabelecimento_login UNIQUE (id_estabelecimento, login),
  CONSTRAINT ck_usuarios_sexo CHECK (sexo IN ('F','M','O')),
  CONSTRAINT ck_usuarios_tipo CHECK (tipo IN ('cliente','profissional','admin')),
  CONSTRAINT ck_usuarios_status CHECK (status IN ('ativo','inativo')),
  CONSTRAINT fk_usuarios_estabelecimento FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento)
);

CREATE INDEX idx_usuarios_tipo_status ON usuarios (tipo, status);
CREATE INDEX idx_usuarios_estabelecimento ON usuarios (id_estabelecimento);

-- ---------------------------------------------------------------------
-- CLIENTES
-- O vinculo composto impede associar o perfil a uma conta de outra
-- empresa.
-- ---------------------------------------------------------------------
CREATE TABLE clientes (
  id_cliente         INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_usuario         INTEGER NOT NULL,
  cpf                VARCHAR(11) DEFAULT NULL,
  data_nascimento    DATE DEFAULT NULL,
  observacoes        TEXT DEFAULT NULL,
  pontos_fidelidade  INTEGER NOT NULL DEFAULT 0,
  data_cadastro      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id_estabelecimento INTEGER NOT NULL,
  CONSTRAINT pk_clientes PRIMARY KEY (id_cliente),
  CONSTRAINT uk_clientes_usuario UNIQUE (id_usuario),
  CONSTRAINT uk_clientes_registro UNIQUE (id_estabelecimento, id_cliente),
  CONSTRAINT uk_estabelecimento_cpf UNIQUE (id_estabelecimento, cpf),
  CONSTRAINT ck_clientes_pontos CHECK (pontos_fidelidade >= 0),
  CONSTRAINT fk_clientes_estabelecimento FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento),
  CONSTRAINT fk_clientes_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_tenant_clientes_id_usuario FOREIGN KEY (id_estabelecimento, id_usuario) REFERENCES usuarios (id_estabelecimento, id_usuario) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_clientes_estabelecimento ON clientes (id_estabelecimento);
CREATE INDEX idx_clientes_tenant_usuario ON clientes (id_estabelecimento, id_usuario);

-- ---------------------------------------------------------------------
-- PROFISSIONAIS
-- Equipe isolada por estabelecimento.
-- ---------------------------------------------------------------------
CREATE TABLE profissionais (
  id_profissional      INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_usuario           INTEGER NOT NULL,
  especialidade        VARCHAR(120) DEFAULT NULL,
  bio                  TEXT DEFAULT NULL,
  foto                 VARCHAR(255) DEFAULT NULL,
  pode_bloquear_agenda SMALLINT NOT NULL DEFAULT 1,
  data_cadastro        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  comissao_percentual  NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  token_calendario     VARCHAR(64) DEFAULT NULL,
  id_estabelecimento   INTEGER NOT NULL,
  CONSTRAINT pk_profissionais PRIMARY KEY (id_profissional),
  CONSTRAINT uk_profissionais_usuario UNIQUE (id_usuario),
  CONSTRAINT uk_profissionais_registro UNIQUE (id_estabelecimento, id_profissional),
  CONSTRAINT fk_profissionais_estabelecimento FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento),
  CONSTRAINT fk_profissionais_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_tenant_profissionais_id_usuario FOREIGN KEY (id_estabelecimento, id_usuario) REFERENCES usuarios (id_estabelecimento, id_usuario) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_profissionais_estabelecimento ON profissionais (id_estabelecimento);
CREATE INDEX idx_profissionais_tenant_usuario ON profissionais (id_estabelecimento, id_usuario);

-- ---------------------------------------------------------------------
-- ADMINISTRADORES LOCAIS
-- Cada empresa tem pelo menos uma conta administrativa criada junto com
-- seu cadastro.
-- ---------------------------------------------------------------------
CREATE TABLE administradores (
  id_administrador   INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_usuario         INTEGER NOT NULL,
  nivel              VARCHAR(7) NOT NULL DEFAULT 'super',
  data_cadastro      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id_estabelecimento INTEGER NOT NULL,
  CONSTRAINT pk_administradores PRIMARY KEY (id_administrador),
  CONSTRAINT uk_administradores_usuario UNIQUE (id_usuario),
  CONSTRAINT uk_administradores_registro UNIQUE (id_estabelecimento, id_administrador),
  CONSTRAINT ck_administradores_nivel CHECK (nivel IN ('super','gerente')),
  CONSTRAINT fk_administradores_estabelecimento FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento),
  CONSTRAINT fk_administradores_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_tenant_administradores_id_usuario FOREIGN KEY (id_estabelecimento, id_usuario) REFERENCES usuarios (id_estabelecimento, id_usuario) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_administradores_estabelecimento ON administradores (id_estabelecimento);
CREATE INDEX idx_administradores_tenant_usuario ON administradores (id_estabelecimento, id_usuario);

-- ---------------------------------------------------------------------
-- SERVICOS
-- Catalogo proprio de cada estabelecimento.
-- ---------------------------------------------------------------------
CREATE TABLE servicos (
  id_servico         INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nome               VARCHAR(120) NOT NULL,
  descricao          TEXT DEFAULT NULL,
  preco              NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  duracao_minutos    SMALLINT NOT NULL DEFAULT 30,
  status             VARCHAR(7) NOT NULL DEFAULT 'ativo',
  destaque           SMALLINT NOT NULL DEFAULT 0,
  data_cadastro      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao   TIMESTAMP DEFAULT NULL,
  id_estabelecimento INTEGER NOT NULL,
  CONSTRAINT pk_servicos PRIMARY KEY (id_servico),
  CONSTRAINT uk_servicos_registro UNIQUE (id_estabelecimento, id_servico),
  CONSTRAINT ck_servicos_status CHECK (status IN ('ativo','inativo')),
  CONSTRAINT fk_servicos_estabelecimento FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento),
  CONSTRAINT ck_servicos_duracao CHECK (duracao_minutos > 0),
  CONSTRAINT ck_servicos_preco CHECK (preco >= 0)
);

CREATE INDEX idx_servicos_status ON servicos (status);
CREATE INDEX idx_servicos_estabelecimento ON servicos (id_estabelecimento);

-- ---------------------------------------------------------------------
-- PROFISSIONAL x SERVICO
-- As chaves compostas impedem vinculos entre empresas diferentes.
-- ---------------------------------------------------------------------
CREATE TABLE profissional_servico (
  id_profissional    INTEGER NOT NULL,
  id_servico         INTEGER NOT NULL,
  id_estabelecimento INTEGER NOT NULL,
  CONSTRAINT pk_profissional_servico PRIMARY KEY (id_profissional, id_servico),
  CONSTRAINT fk_profissional_servico_estabelecimento FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento),
  CONSTRAINT fk_ps_profissional FOREIGN KEY (id_profissional) REFERENCES profissionais (id_profissional) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_ps_servico FOREIGN KEY (id_servico) REFERENCES servicos (id_servico) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_tenant_profissional_servico_id_profissional FOREIGN KEY (id_estabelecimento, id_profissional) REFERENCES profissionais (id_estabelecimento, id_profissional) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_tenant_profissional_servico_id_servico FOREIGN KEY (id_estabelecimento, id_servico) REFERENCES servicos (id_estabelecimento, id_servico) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_ps_servico ON profissional_servico (id_servico);
CREATE INDEX idx_ps_estabelecimento ON profissional_servico (id_estabelecimento);
CREATE INDEX idx_ps_tenant_profissional ON profissional_servico (id_estabelecimento, id_profissional);
CREATE INDEX idx_ps_tenant_servico ON profissional_servico (id_estabelecimento, id_servico);

-- ---------------------------------------------------------------------
-- EXPEDIENTE
-- Faixas semanais dos profissionais da empresa.
-- ---------------------------------------------------------------------
CREATE TABLE horarios_profissionais (
  id_horario         INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_profissional    INTEGER NOT NULL,
  dia_semana         SMALLINT NOT NULL,
  hora_inicio        TIME NOT NULL,
  hora_fim           TIME NOT NULL,
  intervalo_minutos  SMALLINT NOT NULL DEFAULT 30,
  status             VARCHAR(7) NOT NULL DEFAULT 'ativo',
  data_cadastro      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id_estabelecimento INTEGER NOT NULL,
  CONSTRAINT pk_horarios_profissionais PRIMARY KEY (id_horario),
  CONSTRAINT uk_horario_faixa UNIQUE (id_profissional, dia_semana, hora_inicio, hora_fim),
  CONSTRAINT uk_horarios_profissionais_registro UNIQUE (id_estabelecimento, id_horario),
  CONSTRAINT ck_horarios_status CHECK (status IN ('ativo','inativo')),
  CONSTRAINT ck_horarios_intervalo CHECK (intervalo_minutos >= 0),
  CONSTRAINT fk_horarios_profissionais_estabelecimento FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento),
  CONSTRAINT fk_horarios_profissional FOREIGN KEY (id_profissional) REFERENCES profissionais (id_profissional) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_tenant_horarios_profissionais_id_profissional FOREIGN KEY (id_estabelecimento, id_profissional) REFERENCES profissionais (id_estabelecimento, id_profissional) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT ck_horarios_dia CHECK (dia_semana BETWEEN 0 AND 6),
  CONSTRAINT ck_horarios_faixa CHECK (hora_fim > hora_inicio)
);

CREATE INDEX idx_horario_prof_dia ON horarios_profissionais (id_profissional, dia_semana, status);
CREATE INDEX idx_horarios_estabelecimento ON horarios_profissionais (id_estabelecimento);
CREATE INDEX idx_horarios_tenant_profissional ON horarios_profissionais (id_estabelecimento, id_profissional);

-- ---------------------------------------------------------------------
-- BLOQUEIOS
-- Indisponibilidades da agenda.
-- ---------------------------------------------------------------------
CREATE TABLE bloqueios_agenda (
  id_bloqueio        INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_profissional    INTEGER NOT NULL,
  data_bloqueio      DATE NOT NULL,
  hora_inicio        TIME NOT NULL DEFAULT '00:00:00',
  hora_fim           TIME NOT NULL DEFAULT '23:59:59',
  motivo             VARCHAR(255) DEFAULT NULL,
  id_usuario_criou   INTEGER DEFAULT NULL,
  data_criacao       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id_estabelecimento INTEGER NOT NULL,
  CONSTRAINT pk_bloqueios_agenda PRIMARY KEY (id_bloqueio),
  CONSTRAINT uk_bloqueios_agenda_registro UNIQUE (id_estabelecimento, id_bloqueio),
  CONSTRAINT fk_bloqueios_agenda_estabelecimento FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento),
  CONSTRAINT fk_bloqueios_profissional FOREIGN KEY (id_profissional) REFERENCES profissionais (id_profissional) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_bloqueios_usuario FOREIGN KEY (id_usuario_criou) REFERENCES usuarios (id_usuario) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_tenant_bloqueios_agenda_id_profissional FOREIGN KEY (id_estabelecimento, id_profissional) REFERENCES profissionais (id_estabelecimento, id_profissional) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT ck_bloqueio_faixa CHECK (hora_fim > hora_inicio)
);

CREATE INDEX idx_bloqueio_prof_data ON bloqueios_agenda (id_profissional, data_bloqueio);
CREATE INDEX idx_bloqueios_usuario_criou ON bloqueios_agenda (id_usuario_criou);
CREATE INDEX idx_bloqueios_estabelecimento ON bloqueios_agenda (id_estabelecimento);
CREATE INDEX idx_bloqueios_tenant_profissional ON bloqueios_agenda (id_estabelecimento, id_profissional);

-- ---------------------------------------------------------------------
-- AGENDAMENTOS
-- Cliente, profissional e servico precisam pertencer ao mesmo
-- estabelecimento.
-- ---------------------------------------------------------------------
CREATE TABLE agendamentos (
  id_agendamento      INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_cliente          INTEGER NOT NULL,
  id_profissional     INTEGER NOT NULL,
  id_servico          INTEGER NOT NULL,
  data_agendamento    DATE NOT NULL,
  hora_inicio         TIME NOT NULL,
  hora_fim            TIME NOT NULL,
  valor               NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  status              VARCHAR(10) NOT NULL DEFAULT 'agendado',
  observacao          TEXT DEFAULT NULL,
  origem              VARCHAR(12) NOT NULL DEFAULT 'cliente',
  motivo_cancelamento VARCHAR(255) DEFAULT NULL,
  id_usuario_cancelou INTEGER DEFAULT NULL,
  data_criacao        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao    TIMESTAMP DEFAULT NULL,
  grupo_recorrencia   VARCHAR(36) DEFAULT NULL,
  id_cliente_pacote   INTEGER DEFAULT NULL,
  id_estabelecimento  INTEGER NOT NULL,
  CONSTRAINT pk_agendamentos PRIMARY KEY (id_agendamento),
  CONSTRAINT uk_agendamentos_registro UNIQUE (id_estabelecimento, id_agendamento),
  CONSTRAINT ck_agend_status CHECK (status IN ('agendado','confirmado','concluido','cancelado')),
  CONSTRAINT ck_agend_origem CHECK (origem IN ('cliente','admin','profissional')),
  CONSTRAINT fk_agend_cliente FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_agend_profissional FOREIGN KEY (id_profissional) REFERENCES profissionais (id_profissional) ON UPDATE CASCADE,
  CONSTRAINT fk_agend_servico FOREIGN KEY (id_servico) REFERENCES servicos (id_servico) ON UPDATE CASCADE,
  CONSTRAINT fk_agend_usuario_cancelou FOREIGN KEY (id_usuario_cancelou) REFERENCES usuarios (id_usuario) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_agendamentos_estabelecimento FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento),
  CONSTRAINT fk_tenant_agendamentos_id_cliente FOREIGN KEY (id_estabelecimento, id_cliente) REFERENCES clientes (id_estabelecimento, id_cliente) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_tenant_agendamentos_id_profissional FOREIGN KEY (id_estabelecimento, id_profissional) REFERENCES profissionais (id_estabelecimento, id_profissional) ON UPDATE CASCADE,
  CONSTRAINT fk_tenant_agendamentos_id_servico FOREIGN KEY (id_estabelecimento, id_servico) REFERENCES servicos (id_estabelecimento, id_servico) ON UPDATE CASCADE,
  CONSTRAINT ck_agend_horario CHECK (hora_fim > hora_inicio)
);

CREATE INDEX idx_agend_profissional_data ON agendamentos (id_profissional, data_agendamento, hora_inicio);
CREATE INDEX idx_agend_cliente_data ON agendamentos (id_cliente, data_agendamento);
CREATE INDEX idx_agend_status_data ON agendamentos (status, data_agendamento);
CREATE INDEX idx_agend_servico ON agendamentos (id_servico);
CREATE INDEX idx_agend_usuario_cancelou ON agendamentos (id_usuario_cancelou);
CREATE INDEX idx_agendamentos_estabelecimento ON agendamentos (id_estabelecimento);
CREATE INDEX idx_agend_tenant_cliente ON agendamentos (id_estabelecimento, id_cliente);
CREATE INDEX idx_agend_tenant_profissional ON agendamentos (id_estabelecimento, id_profissional);
CREATE INDEX idx_agend_tenant_servico ON agendamentos (id_estabelecimento, id_servico);

-- ---------------------------------------------------------------------
-- RECURSOS DIFERENCIAIS
-- ---------------------------------------------------------------------
CREATE TABLE lista_espera (
  id_lista           INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_estabelecimento INTEGER NOT NULL,
  id_cliente         INTEGER NOT NULL,
  id_servico         INTEGER NOT NULL,
  id_profissional    INTEGER NULL,
  data_desejada      DATE NOT NULL,
  periodo            VARCHAR(8) NOT NULL DEFAULT 'qualquer',
  status             VARCHAR(10) NOT NULL DEFAULT 'aguardando',
  data_aviso         TIMESTAMP NULL,
  data_criacao       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_lista_espera PRIMARY KEY (id_lista),
  CONSTRAINT uk_lista_cliente_preferencia UNIQUE (id_estabelecimento, id_cliente, id_servico, id_profissional, data_desejada),
  CONSTRAINT ck_lista_periodo CHECK (periodo IN ('qualquer','manha','tarde','noite')),
  CONSTRAINT ck_lista_status CHECK (status IN ('aguardando','avisado','convertido','cancelado')),
  CONSTRAINT fk_lista_empresa FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento),
  CONSTRAINT fk_lista_cliente_tenant FOREIGN KEY (id_estabelecimento, id_cliente) REFERENCES clientes (id_estabelecimento, id_cliente) ON DELETE CASCADE,
  CONSTRAINT fk_lista_servico_tenant FOREIGN KEY (id_estabelecimento, id_servico) REFERENCES servicos (id_estabelecimento, id_servico) ON DELETE CASCADE,
  CONSTRAINT fk_lista_profissional_tenant FOREIGN KEY (id_estabelecimento, id_profissional) REFERENCES profissionais (id_estabelecimento, id_profissional) ON DELETE CASCADE
);

CREATE INDEX idx_lista_vaga ON lista_espera (id_estabelecimento, data_desejada, id_profissional, status);

CREATE TABLE notificacoes (
  id_notificacao     INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_estabelecimento INTEGER NOT NULL,
  id_usuario         INTEGER NULL,
  id_agendamento     INTEGER NULL,
  canal              VARCHAR(8) NOT NULL DEFAULT 'sistema',
  tipo               VARCHAR(40) NOT NULL,
  destinatario       VARCHAR(150) NULL,
  mensagem           TEXT NOT NULL,
  status             VARCHAR(9) NOT NULL DEFAULT 'pendente',
  data_programada    TIMESTAMP NULL,
  data_envio         TIMESTAMP NULL,
  tentativas         INTEGER NOT NULL DEFAULT 0,
  erro               VARCHAR(255) NULL,
  data_criacao       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_notificacoes PRIMARY KEY (id_notificacao),
  CONSTRAINT uk_notificacao_agendamento_tipo UNIQUE (id_estabelecimento, id_agendamento, tipo),
  CONSTRAINT ck_notificacao_canal CHECK (canal IN ('whatsapp','email','sistema')),
  CONSTRAINT ck_notificacao_status CHECK (status IN ('pendente','enviada','lida','cancelada')),
  CONSTRAINT fk_notificacao_empresa FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento),
  CONSTRAINT fk_notificacao_usuario_tenant FOREIGN KEY (id_estabelecimento, id_usuario) REFERENCES usuarios (id_estabelecimento, id_usuario) ON DELETE CASCADE,
  CONSTRAINT fk_notificacao_agendamento_tenant FOREIGN KEY (id_estabelecimento, id_agendamento) REFERENCES agendamentos (id_estabelecimento, id_agendamento) ON DELETE CASCADE
);

CREATE INDEX idx_notificacao_fila ON notificacoes (id_estabelecimento, status, data_programada);

CREATE TABLE pagamentos (
  id_pagamento       INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_estabelecimento INTEGER NOT NULL,
  id_agendamento     INTEGER NOT NULL,
  tipo               VARCHAR(8) NOT NULL DEFAULT 'sinal',
  valor              NUMERIC(10,2) NOT NULL,
  metodo             VARCHAR(8) NOT NULL DEFAULT 'pix',
  status             VARCHAR(9) NOT NULL DEFAULT 'pendente',
  referencia         VARCHAR(80) NULL,
  data_pagamento     TIMESTAMP NULL,
  data_criacao       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_pagamentos PRIMARY KEY (id_pagamento),
  CONSTRAINT uk_pagamento_agendamento_tipo UNIQUE (id_estabelecimento, id_agendamento, tipo),
  CONSTRAINT ck_pagamento_tipo CHECK (tipo IN ('sinal','integral')),
  CONSTRAINT ck_pagamento_metodo CHECK (metodo IN ('pix','dinheiro','cartao','outro')),
  CONSTRAINT ck_pagamento_status CHECK (status IN ('pendente','pago','cancelado','estornado')),
  CONSTRAINT fk_pagamento_empresa FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento),
  CONSTRAINT fk_pagamento_agendamento_tenant FOREIGN KEY (id_estabelecimento, id_agendamento) REFERENCES agendamentos (id_estabelecimento, id_agendamento) ON DELETE CASCADE
);

CREATE INDEX idx_pagamento_status ON pagamentos (id_estabelecimento, status);

CREATE TABLE fidelidade_movimentos (
  id_movimento       INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_estabelecimento INTEGER NOT NULL,
  id_cliente         INTEGER NOT NULL,
  id_agendamento     INTEGER NULL,
  pontos             INTEGER NOT NULL,
  descricao          VARCHAR(180) NOT NULL,
  data_criacao       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_fidelidade_movimentos PRIMARY KEY (id_movimento),
  CONSTRAINT uk_fidelidade_agendamento UNIQUE (id_estabelecimento, id_agendamento),
  CONSTRAINT fk_fidelidade_empresa FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento),
  CONSTRAINT fk_fidelidade_cliente_tenant FOREIGN KEY (id_estabelecimento, id_cliente) REFERENCES clientes (id_estabelecimento, id_cliente) ON DELETE CASCADE,
  CONSTRAINT fk_fidelidade_agendamento_tenant FOREIGN KEY (id_estabelecimento, id_agendamento) REFERENCES agendamentos (id_estabelecimento, id_agendamento) ON DELETE CASCADE
);

CREATE INDEX idx_fidelidade_cliente ON fidelidade_movimentos (id_estabelecimento, id_cliente);

CREATE TABLE pacotes (
  id_pacote          INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_estabelecimento INTEGER NOT NULL,
  id_servico         INTEGER NOT NULL,
  nome               VARCHAR(120) NOT NULL,
  quantidade         SMALLINT NOT NULL,
  validade_dias      SMALLINT NOT NULL DEFAULT 90,
  preco              NUMERIC(10,2) NOT NULL,
  status             VARCHAR(7) NOT NULL DEFAULT 'ativo',
  data_criacao       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_pacotes PRIMARY KEY (id_pacote),
  CONSTRAINT uk_estabelecimento_pacote UNIQUE (id_estabelecimento, id_pacote),
  CONSTRAINT ck_pacote_status CHECK (status IN ('ativo','inativo')),
  CONSTRAINT ck_pacote_quantidade CHECK (quantidade >= 0),
  CONSTRAINT ck_pacote_validade CHECK (validade_dias >= 0),
  CONSTRAINT fk_pacote_empresa FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento),
  CONSTRAINT fk_pacote_servico_tenant FOREIGN KEY (id_estabelecimento, id_servico) REFERENCES servicos (id_estabelecimento, id_servico)
);

CREATE INDEX idx_pacote_status ON pacotes (id_estabelecimento, status);

CREATE TABLE cliente_pacotes (
  id_cliente_pacote  INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_estabelecimento INTEGER NOT NULL,
  id_cliente         INTEGER NOT NULL,
  id_pacote          INTEGER NOT NULL,
  creditos_total     SMALLINT NOT NULL,
  creditos_restantes SMALLINT NOT NULL,
  status_pagamento   VARCHAR(9) NOT NULL DEFAULT 'pendente',
  data_expiracao     DATE NOT NULL,
  data_criacao       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_cliente_pacotes PRIMARY KEY (id_cliente_pacote),
  CONSTRAINT uk_estabelecimento_cliente_pacote UNIQUE (id_estabelecimento, id_cliente_pacote),
  CONSTRAINT ck_cliente_pacote_status CHECK (status_pagamento IN ('pendente','pago','cancelado')),
  CONSTRAINT ck_cliente_pacote_total CHECK (creditos_total >= 0),
  CONSTRAINT ck_cliente_pacote_restantes CHECK (creditos_restantes >= 0),
  CONSTRAINT fk_cliente_pacote_empresa FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento),
  CONSTRAINT fk_cliente_pacote_cliente_tenant FOREIGN KEY (id_estabelecimento, id_cliente) REFERENCES clientes (id_estabelecimento, id_cliente) ON DELETE CASCADE,
  CONSTRAINT fk_cliente_pacote_pacote_tenant FOREIGN KEY (id_estabelecimento, id_pacote) REFERENCES pacotes (id_estabelecimento, id_pacote)
);

CREATE INDEX idx_cliente_pacotes ON cliente_pacotes (id_estabelecimento, id_cliente, status_pagamento);

CREATE TABLE avaliacoes (
  id_avaliacao       INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_estabelecimento INTEGER NOT NULL,
  id_agendamento     INTEGER NOT NULL,
  id_cliente         INTEGER NOT NULL,
  id_profissional    INTEGER NOT NULL,
  nota               SMALLINT NOT NULL,
  comentario         VARCHAR(500) NULL,
  status             VARCHAR(9) NOT NULL DEFAULT 'publicada',
  data_criacao       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_avaliacoes PRIMARY KEY (id_avaliacao),
  CONSTRAINT uk_avaliacao_agendamento UNIQUE (id_estabelecimento, id_agendamento),
  CONSTRAINT ck_avaliacao_status CHECK (status IN ('publicada','oculta')),
  CONSTRAINT fk_avaliacao_empresa FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento),
  CONSTRAINT fk_avaliacao_agendamento_tenant FOREIGN KEY (id_estabelecimento, id_agendamento) REFERENCES agendamentos (id_estabelecimento, id_agendamento) ON DELETE CASCADE,
  CONSTRAINT fk_avaliacao_cliente_tenant FOREIGN KEY (id_estabelecimento, id_cliente) REFERENCES clientes (id_estabelecimento, id_cliente) ON DELETE CASCADE,
  CONSTRAINT fk_avaliacao_profissional_tenant FOREIGN KEY (id_estabelecimento, id_profissional) REFERENCES profissionais (id_estabelecimento, id_profissional),
  CONSTRAINT ck_avaliacao_nota CHECK (nota BETWEEN 1 AND 5)
);

CREATE INDEX idx_avaliacao_profissional ON avaliacoes (id_estabelecimento, id_profissional, status);

-- ---------------------------------------------------------------------
-- LOG DE AUTENTICACAO
-- Nome e CPF ficam desnormalizados de proposito: o log precisa
-- sobreviver a exclusao do usuario feita pelo master.
-- ---------------------------------------------------------------------
CREATE TABLE logs_autenticacao (
  id_log             INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_estabelecimento INTEGER NOT NULL,
  id_usuario         INTEGER DEFAULT NULL,
  login_informado    VARCHAR(150) NOT NULL,
  nome               VARCHAR(120) NOT NULL DEFAULT '',
  cpf                VARCHAR(11) DEFAULT NULL,
  perfil             VARCHAR(20) DEFAULT NULL,
  evento             VARCHAR(13) NOT NULL,
  fator_2fa          VARCHAR(15) DEFAULT NULL,
  ip                 VARCHAR(45) DEFAULT NULL,
  data_hora          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_logs_autenticacao PRIMARY KEY (id_log),
  CONSTRAINT ck_logs_evento CHECK (evento IN ('login_sucesso','login_falha','2fa_sucesso','2fa_falha','2fa_bloqueio','logout')),
  CONSTRAINT ck_logs_fator CHECK (fator_2fa IN ('nome_materno','data_nascimento','cep','totp')),
  CONSTRAINT fk_logs_estabelecimento FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento)
);

CREATE INDEX idx_logs_estabelecimento ON logs_autenticacao (id_estabelecimento, data_hora);
CREATE INDEX idx_logs_nome ON logs_autenticacao (nome);
CREATE INDEX idx_logs_cpf ON logs_autenticacao (cpf);

-- ---------------------------------------------------------------------
-- PLANOS DE CONTRATACAO
-- Tetos que a administracao master aplica a um estabelecimento: equipe,
-- catalogo e volume de agendamentos no mes.
--
-- Limite NULL significa "sem teto", e estabelecimento sem vinculo continua
-- sem limite nenhum: a funcionalidade nasce sem mudar quem ja usa o sistema.
-- ---------------------------------------------------------------------
CREATE TABLE planos (
  id_plano                INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nome                    VARCHAR(60) NOT NULL,
  descricao               VARCHAR(255) DEFAULT NULL,
  limite_profissionais    INTEGER DEFAULT NULL,
  limite_servicos         INTEGER DEFAULT NULL,
  limite_agendamentos_mes INTEGER DEFAULT NULL,
  status                  VARCHAR(10) NOT NULL DEFAULT 'ativo',
  data_criacao            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_planos PRIMARY KEY (id_plano),
  CONSTRAINT uk_planos_nome UNIQUE (nome),
  CONSTRAINT ck_planos_status CHECK (status IN ('ativo','inativo'))
);

-- Um estabelecimento tem um plano de cada vez: a chave primaria e o proprio
-- vinculo, entao a troca substitui a linha em vez de empilhar historico.
CREATE TABLE estabelecimento_plano (
  id_estabelecimento INTEGER NOT NULL,
  id_plano           INTEGER NOT NULL,
  data_inicio        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  observacao         VARCHAR(255) DEFAULT NULL,
  CONSTRAINT pk_estabelecimento_plano PRIMARY KEY (id_estabelecimento),
  CONSTRAINT fk_ep_estabelecimento FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento),
  CONSTRAINT fk_ep_plano FOREIGN KEY (id_plano) REFERENCES planos (id_plano)
);

CREATE INDEX idx_ep_plano ON estabelecimento_plano (id_plano);

-- ---------------------------------------------------------------------
-- AUDITORIA DA ADMINISTRACAO MASTER
-- Registro do que a conta global faz: empresas criadas, acessos ligados e
-- desligados, senhas redefinidas e bloqueios liberados.
--
-- Nome do master e nome da empresa ficam gravados na propria linha, e nao por
-- chave estrangeira: o historico precisa continuar legivel depois que a conta
-- ou o estabelecimento citado deixar de existir.
-- ---------------------------------------------------------------------
CREATE TABLE logs_master (
  id_log_master        BIGINT GENERATED BY DEFAULT AS IDENTITY,
  id_master            INTEGER DEFAULT NULL,
  master_nome          VARCHAR(120) NOT NULL DEFAULT '',
  master_email         VARCHAR(150) NOT NULL DEFAULT '',
  acao                 VARCHAR(40) NOT NULL,
  id_estabelecimento   INTEGER DEFAULT NULL,
  estabelecimento_nome VARCHAR(120) DEFAULT NULL,
  alvo                 VARCHAR(150) DEFAULT NULL,
  detalhe              VARCHAR(255) DEFAULT NULL,
  ip                   VARCHAR(45) DEFAULT NULL,
  data_hora            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_logs_master PRIMARY KEY (id_log_master)
);

CREATE INDEX idx_logs_master_data ON logs_master (data_hora);
CREATE INDEX idx_logs_master_acao ON logs_master (acao);
CREATE INDEX idx_logs_master_empresa ON logs_master (id_estabelecimento, data_hora);

-- ---------------------------------------------------------------------
-- TENTATIVAS DE ACESSO
-- Contador usado pelo controle de forca bruta (includes/seguranca.php).
--
-- Fica fora do escopo de estabelecimento de proposito: o bloqueio protege
-- tambem a area master, que nao pertence a empresa nenhuma. Guarda apenas o
-- hash da origem, nunca o e-mail ou o IP em texto claro.
-- ---------------------------------------------------------------------
CREATE TABLE tentativas_acesso (
  id_tentativa  BIGINT GENERATED BY DEFAULT AS IDENTITY,
  escopo        VARCHAR(30) NOT NULL,
  chave         CHAR(64) NOT NULL,
  data_hora     TIMESTAMP NOT NULL,
  CONSTRAINT pk_tentativas_acesso PRIMARY KEY (id_tentativa)
);

CREATE INDEX idx_tentativa_busca ON tentativas_acesso (escopo, chave, data_hora);

-- ---------------------------------------------------------------------
-- CONFIGURACOES
-- Regras independentes para cada estabelecimento.
-- ---------------------------------------------------------------------
CREATE TABLE configuracoes (
  id_configuracao    INTEGER GENERATED BY DEFAULT AS IDENTITY,
  chave              VARCHAR(60) NOT NULL,
  valor              VARCHAR(255) NOT NULL,
  descricao          VARCHAR(255) DEFAULT NULL,
  id_estabelecimento INTEGER NOT NULL,
  CONSTRAINT pk_configuracoes PRIMARY KEY (id_configuracao),
  CONSTRAINT uk_configuracoes_registro UNIQUE (id_estabelecimento, id_configuracao),
  CONSTRAINT uk_estabelecimento_chave UNIQUE (id_estabelecimento, chave),
  CONSTRAINT fk_configuracoes_estabelecimento FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento)
);

CREATE INDEX idx_configuracoes_estabelecimento ON configuracoes (id_estabelecimento);

-- =====================================================================
-- DADOS INICIAIS
-- Os usuarios (admin, profissionais e cliente demo) sao criados pelo
-- arquivo instalar.php, que usa password_hash() do PHP.
-- =====================================================================

-- O horario usa a forma E'...' porque, ao contrario do MySQL, o
-- PostgreSQL so interpreta \n como quebra de linha nesse formato.
INSERT INTO estabelecimento
  (nome,slug,slogan,descricao,telefone,whatsapp,email,endereco,bairro,cidade,uf,cep,horario_funcionamento)
VALUES
  ('Agendei Studio', 'agendei-studio',
   'Atendimento com hora marcada, do jeito que voce precisa.',
   'Somos um estudio de beleza e bem-estar com profissionais qualificados e atendimento personalizado. Trabalhamos com hora marcada para que voce nao perca tempo em filas de espera.',
   '(11) 3000-0000', '(11) 99000-0000', 'contato@agendei.com.br',
   'Rua das Acacias, 120', 'Centro', 'Sao Paulo', 'SP', '01000-000',
   E'Segunda a sexta: 08:00 as 19:00\nSabado: 08:00 as 14:00\nDomingo: fechado');

-- Valores iniciais das regras que podem ser ajustadas pelo painel administrativo.
INSERT INTO configuracoes (id_estabelecimento,chave,valor,descricao) VALUES
  (1, 'antecedencia_minima_horas', '2',  'Antecedencia minima, em horas, para o cliente agendar'),
  (1, 'antecedencia_maxima_dias',  '60', 'Quantos dias no futuro o cliente pode agendar'),
  (1, 'cancelamento_limite_horas', '4',  'Ate quantas horas antes o cliente pode cancelar'),
  (1, 'intervalo_slots_minutos',   '30', 'Intervalo padrao entre horarios exibidos'),
  (1, 'permitir_bloqueio_profissional', '1', 'Profissional pode bloquear a propria agenda (1=sim, 0=nao)'),
  (1, 'confirmar_automaticamente', '0',  'Agendamentos nascem confirmados (1=sim, 0=nao)');

-- Servicos de exemplo usados para demonstrar o catalogo e a criacao de reservas.
INSERT INTO servicos (id_estabelecimento,nome,descricao,preco,duracao_minutos,status,destaque) VALUES
  (1, 'Corte de cabelo masculino', 'Corte na tesoura ou maquina, com finalizacao e acabamento na navalha.', 45.00, 30, 'ativo', 1),
  (1, 'Corte de cabelo feminino',  'Corte personalizado com lavagem e escova de finalizacao.', 75.00, 60, 'ativo', 1),
  (1, 'Barba completa',            'Toalha quente, navalha, hidratacao e finalizacao.', 35.00, 30, 'ativo', 1),
  (1, 'Corte + barba',             'Combo com corte de cabelo e barba completa.', 70.00, 60, 'ativo', 1),
  (1, 'Coloracao',                 'Coloracao profissional com produtos de alta performance.', 160.00, 120, 'ativo', 0),
  (1, 'Hidratacao capilar',        'Tratamento profundo de reconstrucao e brilho.', 90.00, 60, 'ativo', 0),
  (1, 'Manicure',                  'Cuidado completo das unhas das maos com esmaltacao.', 40.00, 45, 'ativo', 0),
  (1, 'Pedicure',                  'Cuidado completo das unhas dos pes com esmaltacao.', 45.00, 45, 'ativo', 0);

-- =====================================================================
-- Filiais (unidades). Cada profissional pertence a uma; cada agendamento
-- grava em qual foi marcado. A foto vai em base64 (TEXT).
-- Para atualizar uma base ja existente use: php scripts/migrar_filiais.php
-- =====================================================================
DROP TABLE IF EXISTS filiais CASCADE;
CREATE TABLE filiais (
  id_filial          INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_estabelecimento INTEGER NOT NULL,
  nome               VARCHAR(120) NOT NULL,
  telefone           VARCHAR(20) DEFAULT NULL,
  cep                CHAR(8) DEFAULT NULL,
  logradouro         VARCHAR(150) DEFAULT NULL,
  numero             VARCHAR(20) DEFAULT NULL,
  complemento        VARCHAR(60) DEFAULT NULL,
  bairro             VARCHAR(100) DEFAULT NULL,
  cidade             VARCHAR(100) DEFAULT NULL,
  uf                 CHAR(2) DEFAULT NULL,
  foto               TEXT DEFAULT NULL,
  status             VARCHAR(7) NOT NULL DEFAULT 'ativo',
  ordem              SMALLINT NOT NULL DEFAULT 0,
  data_cadastro      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_filiais PRIMARY KEY (id_filial),
  CONSTRAINT uk_filiais_registro UNIQUE (id_estabelecimento, id_filial),
  CONSTRAINT ck_filiais_status CHECK (status IN ('ativo','inativo')),
  CONSTRAINT fk_filiais_estabelecimento FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento)
);
CREATE INDEX idx_filiais_estabelecimento ON filiais (id_estabelecimento, status);

ALTER TABLE profissionais ADD COLUMN id_filial INTEGER DEFAULT NULL;
ALTER TABLE profissionais ADD CONSTRAINT fk_profissionais_filial FOREIGN KEY (id_filial) REFERENCES filiais (id_filial);
CREATE INDEX idx_profissionais_filial ON profissionais (id_estabelecimento, id_filial);

ALTER TABLE agendamentos ADD COLUMN id_filial INTEGER DEFAULT NULL;
ALTER TABLE agendamentos ADD CONSTRAINT fk_agendamentos_filial FOREIGN KEY (id_filial) REFERENCES filiais (id_filial);
CREATE INDEX idx_agendamentos_filial ON agendamentos (id_estabelecimento, id_filial);

-- Toda instalacao nasce com uma unidade: a Matriz do estabelecimento semeado.
INSERT INTO filiais (id_estabelecimento, nome, status, ordem)
SELECT id_estabelecimento, 'Matriz', 'ativo', 0 FROM estabelecimento WHERE slug = 'agendei-studio';

-- ---------------------------------------------------------------------
-- SESSOES LEMBRADAS ("manter conectado")
-- Guarda so o hash do segredo do cookie; o segredo em si vive no navegador.
-- Para atualizar uma base ja existente use: php scripts/migrar_lembrar.php
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS sessoes_lembradas CASCADE;
CREATE TABLE sessoes_lembradas (
  id_sessao          INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_estabelecimento INTEGER NOT NULL,
  id_usuario         INTEGER NOT NULL,
  seletor            CHAR(24) NOT NULL,
  validador_hash     CHAR(64) NOT NULL,
  expira_em          TIMESTAMP NOT NULL,
  criado_em          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultimo_uso         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_sessoes_lembradas PRIMARY KEY (id_sessao),
  CONSTRAINT uk_sessoes_lembradas_seletor UNIQUE (seletor),
  CONSTRAINT fk_sessoes_lembradas_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario) ON DELETE CASCADE
);
CREATE INDEX idx_sessoes_lembradas_usuario ON sessoes_lembradas (id_estabelecimento, id_usuario);
CREATE INDEX idx_sessoes_lembradas_expira ON sessoes_lembradas (expira_em);
