<?php
/** Exclusao com FKs reais do esquema PostgreSQL, adaptado ao SQLite em memoria. */
if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}
require __DIR__ . '/../models/Estabelecimento.php';

function bd(): PDO
{
    static $db;
    if (!$db) {
        $db = new PDO('sqlite::memory:', null, null, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]);
        $db->exec('PRAGMA foreign_keys = ON');
    }
    return $db;
}

$checagens = 0;
function verificar(bool $condicao, string $mensagem): void
{
    global $checagens;
    if (!$condicao) throw new RuntimeException($mensagem);
    $checagens++;
}

// Preserva todas as FKs e CHECKs; so adapta a sintaxe de geracao dos IDs.
$esquema = file_get_contents(__DIR__ . '/../banco_postgres.sql');
preg_match_all('/^CREATE TABLE (\w+) \([\s\S]*?^\);/m', $esquema, $criacao, PREG_SET_ORDER);
$tabelasLocais = [];
foreach ($criacao as $tabela) {
    $sql = preg_replace('/(?:BIGINT|INTEGER) GENERATED BY DEFAULT AS IDENTITY/', 'INTEGER', $tabela[0]);
    bd()->exec($sql);
    if (str_contains($sql, 'REFERENCES estabelecimento ')) $tabelasLocais[] = $tabela[1];
}
// As colunas id_filial entram no esquema por ALTER TABLE, que o laco acima nao
// executa. O SQLite aceita FK em coluna nova com padrao NULL, entao a ordem de
// exclusao (filiais depois de profissionais e agendamentos) fica coberta.
foreach (['profissionais', 'agendamentos'] as $alterada) {
    bd()->exec('ALTER TABLE ' . $alterada . ' ADD COLUMN id_filial INTEGER DEFAULT NULL REFERENCES filiais (id_filial)');
}
verificar(count($tabelasLocais) === 20, 'Cobertura das tabelas locais mudou; atualize o teste.');

function inserir(string $tabela, array $dados): int
{
    $q = bd()->prepare('INSERT INTO ' . $tabela . ' (' . implode(',', array_keys($dados)) . ') VALUES (' . implode(',', array_fill(0, count($dados), '?')) . ')');
    $q->execute(array_values($dados));
    return (int) bd()->lastInsertId();
}

$plano = inserir('planos', ['nome' => 'Compartilhado']);
$master = inserir('administradores_master', ['nome' => 'Master', 'email' => 'master@teste.local', 'senha_hash' => 'fixture']);
$empresas = [];
foreach (['empresa-a', 'empresa-b'] as $slug) {
    $id = Estabelecimento::contratar(['estabelecimento' => $slug, 'slug' => $slug, 'nome' => 'Responsavel', 'email' => 'admin@teste.local', 'senha' => 'SenhaTeste123!']);
    $empresas[] = $id;
    $vinculo = ['id_estabelecimento' => $id];
    $idClienteUsuario = inserir('usuarios', $vinculo + ['nome' => 'Cliente', 'email' => 'cliente@teste.local', 'senha_hash' => 'fixture', 'tipo' => 'cliente']);
    $idProfUsuario = inserir('usuarios', $vinculo + ['nome' => 'Profissional', 'email' => 'prof@teste.local', 'senha_hash' => 'fixture', 'tipo' => 'profissional']);
    $filial = inserir('filiais', $vinculo + ['nome' => 'Matriz']);
    $cliente = inserir('clientes', $vinculo + ['id_usuario' => $idClienteUsuario]);
    $profissional = inserir('profissionais', $vinculo + ['id_usuario' => $idProfUsuario, 'id_filial' => $filial]);
    $servico = inserir('servicos', $vinculo + ['nome' => 'Servico']);
    inserir('profissional_servico', $vinculo + ['id_profissional' => $profissional, 'id_servico' => $servico]);
    inserir('horarios_profissionais', $vinculo + ['id_profissional' => $profissional, 'dia_semana' => 1, 'hora_inicio' => '08:00', 'hora_fim' => '18:00']);
    inserir('bloqueios_agenda', $vinculo + ['id_profissional' => $profissional, 'data_bloqueio' => '2026-10-01', 'id_usuario_criou' => $idProfUsuario]);
    $agendamento = inserir('agendamentos', $vinculo + ['id_cliente' => $cliente, 'id_profissional' => $profissional, 'id_servico' => $servico, 'id_filial' => $filial, 'data_agendamento' => '2026-10-02', 'hora_inicio' => '10:00', 'hora_fim' => '11:00', 'valor' => 100]);
    inserir('notificacoes', $vinculo + ['id_usuario' => $idClienteUsuario, 'id_agendamento' => $agendamento, 'tipo' => 'lembrete', 'mensagem' => 'Teste']);
    inserir('pagamentos', $vinculo + ['id_agendamento' => $agendamento, 'valor' => 20]);
    inserir('fidelidade_movimentos', $vinculo + ['id_cliente' => $cliente, 'id_agendamento' => $agendamento, 'pontos' => 10, 'descricao' => 'Teste']);
    inserir('avaliacoes', $vinculo + ['id_agendamento' => $agendamento, 'id_cliente' => $cliente, 'id_profissional' => $profissional, 'nota' => 5]);
    $pacote = inserir('pacotes', $vinculo + ['id_servico' => $servico, 'nome' => 'Pacote', 'quantidade' => 5, 'preco' => 100]);
    inserir('cliente_pacotes', $vinculo + ['id_cliente' => $cliente, 'id_pacote' => $pacote, 'creditos_total' => 5, 'creditos_restantes' => 4, 'data_expiracao' => '2026-12-31']);
    inserir('lista_espera', $vinculo + ['id_cliente' => $cliente, 'id_servico' => $servico, 'id_profissional' => $profissional, 'data_desejada' => '2026-10-02']);
    inserir('logs_autenticacao', $vinculo + ['id_usuario' => $idClienteUsuario, 'login_informado' => 'cliente@teste.local', 'evento' => 'login_sucesso']);
    inserir('configuracoes', $vinculo + ['chave' => 'teste', 'valor' => '1']);
    inserir('estabelecimento_plano', $vinculo + ['id_plano' => $plano]);
    inserir('logs_master', $vinculo + ['id_master' => $master, 'acao' => 'estabelecimento_criado', 'estabelecimento_nome' => $slug]);
}

function retrato(int $id): array
{
    global $tabelasLocais;
    $dados = [];
    foreach (array_merge(['estabelecimento'], $tabelasLocais) as $tabela) {
        $q = bd()->prepare('SELECT * FROM ' . $tabela . ' WHERE id_estabelecimento = ?');
        $q->execute([$id]);
        $dados[$tabela] = $q->fetchAll();
    }
    return $dados;
}
[$alvo, $vizinha] = $empresas;
$antes = retrato($alvo);
$outraAntes = retrato($vizinha);
foreach ($antes as $tabela => $linhas) verificar(count($linhas) > 0, 'Fixture vazia: ' . $tabela);

// Uma falha no fim deve restaurar ate os filhos ja removidos no inicio.
bd()->exec('CREATE TRIGGER impedir_exclusao BEFORE DELETE ON estabelecimento BEGIN SELECT RAISE(ABORT, \'falha simulada\'); END');
$falhou = false;
try {
    Estabelecimento::excluirGlobal($alvo);
} catch (PDOException $erro) {
    $falhou = true;
}
verificar($falhou, 'Falha do banco nao foi propagada.');
verificar(!bd()->inTransaction(), 'Transacao ficou aberta.');
verificar(retrato($alvo) === $antes, 'Falha removeu dados parcialmente.');
bd()->exec('DROP TRIGGER impedir_exclusao');

verificar(Estabelecimento::excluirGlobal($alvo), 'Empresa nao foi excluida.');
foreach (retrato($alvo) as $tabela => $linhas) verificar($linhas === [], 'Restaram dados em ' . $tabela);
verificar(retrato($vizinha) === $outraAntes, 'Exclusao alterou a outra empresa.');
verificar((int) bd()->query('SELECT COUNT(*) FROM logs_master')->fetchColumn() === 2, 'Auditoria foi apagada.');
verificar((int) bd()->query('SELECT COUNT(*) FROM planos')->fetchColumn() === 1, 'Plano compartilhado foi apagado.');
verificar((int) bd()->query('SELECT COUNT(*) FROM administradores_master')->fetchColumn() === 1, 'Conta master foi apagada.');
verificar(!Estabelecimento::excluirGlobal($alvo), 'Exclusao repetida reportou sucesso.');
verificar(!Estabelecimento::excluirGlobal(0), 'ID invalido foi aceito.');
verificar(bd()->query('PRAGMA foreign_key_check')->fetchAll() === [], 'Restaram vinculos invalidos.');
verificar(Estabelecimento::excluirGlobal($vizinha), 'Ultima empresa nao pode ser excluida.');
echo "OK: {$checagens} verificacoes de exclusao, isolamento e rollback.\n";
