-- Atualizacao do Agendei: aplicar em transacao, nunca importar o dump de instalacao.
SET lock_timeout = '10s';
CREATE TABLE IF NOT EXISTS assinaturas (
  id_estabelecimento INTEGER NOT NULL,
  status VARCHAR(12) NOT NULL DEFAULT 'ativa',
  data_inicio_demo TIMESTAMP DEFAULT NULL,
  data_fim_demo TIMESTAMP DEFAULT NULL,
  metodo_pagamento VARCHAR(12) DEFAULT NULL,
  data_solicitacao TIMESTAMP DEFAULT NULL,
  data_pagamento TIMESTAMP DEFAULT NULL,
  CONSTRAINT pk_assinaturas PRIMARY KEY (id_estabelecimento),
  CONSTRAINT ck_assinaturas_status CHECK (status IN ('demo','pendente','ativa','bloqueada')),
  CONSTRAINT ck_assinaturas_metodo CHECK (metodo_pagamento IS NULL OR metodo_pagamento IN ('pix','boleto','cartao')),
  CONSTRAINT fk_assinaturas_estabelecimento FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento) ON DELETE CASCADE
);
ALTER TABLE assinaturas ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS planos (
  id_plano                INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nome                    VARCHAR(60) NOT NULL,
  descricao               VARCHAR(255) DEFAULT NULL,
  limite_profissionais    INTEGER DEFAULT NULL,
  limite_servicos         INTEGER DEFAULT NULL,
  limite_agendamentos_mes INTEGER DEFAULT NULL,
  status                  VARCHAR(10) NOT NULL DEFAULT 'ativo',
  data_criacao            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_planos PRIMARY KEY (id_plano),
  CONSTRAINT uk_planos_nome UNIQUE (nome),
  CONSTRAINT ck_planos_status CHECK (status IN ('ativo','inativo'))
);
ALTER TABLE planos ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS estabelecimento_plano (
  id_estabelecimento INTEGER NOT NULL,
  id_plano           INTEGER NOT NULL,
  data_inicio        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  observacao         VARCHAR(255) DEFAULT NULL,
  CONSTRAINT pk_estabelecimento_plano PRIMARY KEY (id_estabelecimento),
  CONSTRAINT fk_ep_estabelecimento FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento),
  CONSTRAINT fk_ep_plano FOREIGN KEY (id_plano) REFERENCES planos (id_plano)
);
ALTER TABLE estabelecimento_plano ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS logs_master (
  id_log_master        BIGINT GENERATED BY DEFAULT AS IDENTITY,
  id_master            INTEGER DEFAULT NULL,
  master_nome          VARCHAR(120) NOT NULL DEFAULT '',
  master_email         VARCHAR(150) NOT NULL DEFAULT '',
  acao                 VARCHAR(40) NOT NULL,
  id_estabelecimento   INTEGER DEFAULT NULL,
  estabelecimento_nome VARCHAR(120) DEFAULT NULL,
  alvo                 VARCHAR(150) DEFAULT NULL,
  detalhe              VARCHAR(255) DEFAULT NULL,
  ip                   VARCHAR(45) DEFAULT NULL,
  data_hora            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_logs_master PRIMARY KEY (id_log_master)
);
ALTER TABLE logs_master ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS tentativas_acesso (
  id_tentativa  BIGINT GENERATED BY DEFAULT AS IDENTITY,
  escopo        VARCHAR(30) NOT NULL,
  chave         CHAR(64) NOT NULL,
  data_hora     TIMESTAMP NOT NULL,
  CONSTRAINT pk_tentativas_acesso PRIMARY KEY (id_tentativa)
);
ALTER TABLE tentativas_acesso ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS filiais (
  id_filial          INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_estabelecimento INTEGER NOT NULL,
  nome               VARCHAR(120) NOT NULL,
  telefone           VARCHAR(20) DEFAULT NULL,
  cep                CHAR(8) DEFAULT NULL,
  logradouro         VARCHAR(150) DEFAULT NULL,
  numero             VARCHAR(20) DEFAULT NULL,
  complemento        VARCHAR(60) DEFAULT NULL,
  bairro             VARCHAR(100) DEFAULT NULL,
  cidade             VARCHAR(100) DEFAULT NULL,
  uf                 CHAR(2) DEFAULT NULL,
  foto               TEXT DEFAULT NULL,
  status             VARCHAR(7) NOT NULL DEFAULT 'ativo',
  ordem              SMALLINT NOT NULL DEFAULT 0,
  data_cadastro      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_filiais PRIMARY KEY (id_filial),
  CONSTRAINT uk_filiais_registro UNIQUE (id_estabelecimento, id_filial),
  CONSTRAINT ck_filiais_status CHECK (status IN ('ativo','inativo')),
  CONSTRAINT fk_filiais_estabelecimento FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento)
);
ALTER TABLE filiais ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS vinculos (
  id_vinculo         INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_estabelecimento INTEGER NOT NULL,
  id_usuario         INTEGER NOT NULL,
  tipo               VARCHAR(12) NOT NULL DEFAULT 'cliente',
  status             VARCHAR(7) NOT NULL DEFAULT 'ativo',
  login              VARCHAR(6) DEFAULT NULL,
  ultimo_acesso      TIMESTAMP DEFAULT NULL,
  data_criacao       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_vinculos PRIMARY KEY (id_vinculo),
  CONSTRAINT uk_vinculos_registro UNIQUE (id_estabelecimento, id_vinculo),
  CONSTRAINT uk_vinculos_pessoa_tipo UNIQUE (id_estabelecimento, id_usuario, tipo),
  CONSTRAINT uk_vinculos_login UNIQUE (id_estabelecimento, login),
  CONSTRAINT ck_vinculos_tipo CHECK (tipo IN ('cliente','profissional','admin')),
  CONSTRAINT ck_vinculos_status CHECK (status IN ('ativo','inativo')),
  CONSTRAINT fk_vinculos_estabelecimento FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento),
  CONSTRAINT fk_vinculos_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario) ON DELETE CASCADE ON UPDATE CASCADE
);
ALTER TABLE vinculos ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS sessoes_lembradas (
  id_sessao          INTEGER GENERATED BY DEFAULT AS IDENTITY,
  id_estabelecimento INTEGER NOT NULL,
  id_usuario         INTEGER NOT NULL,
  id_vinculo         INTEGER NOT NULL,
  seletor            CHAR(24) NOT NULL,
  validador_hash     CHAR(64) NOT NULL,
  expira_em          TIMESTAMP NOT NULL,
  criado_em          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultimo_uso         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_sessoes_lembradas PRIMARY KEY (id_sessao),
  CONSTRAINT uk_sessoes_lembradas_seletor UNIQUE (seletor),
  CONSTRAINT fk_sessoes_lembradas_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario) ON DELETE CASCADE,
  CONSTRAINT fk_sessoes_lembradas_vinculo FOREIGN KEY (id_vinculo) REFERENCES vinculos (id_vinculo) ON DELETE CASCADE
);
ALTER TABLE sessoes_lembradas ENABLE ROW LEVEL SECURITY;

ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS totp_segredo VARCHAR(255), ADD COLUMN IF NOT EXISTS totp_ativado_em TIMESTAMP, ADD COLUMN IF NOT EXISTS totp_ultimo_contador BIGINT;
ALTER TABLE administradores_master ADD COLUMN IF NOT EXISTS totp_segredo VARCHAR(255), ADD COLUMN IF NOT EXISTS totp_ativado_em TIMESTAMP, ADD COLUMN IF NOT EXISTS totp_ultimo_contador BIGINT;
ALTER TABLE notificacoes ADD COLUMN IF NOT EXISTS tentativas INTEGER NOT NULL DEFAULT 0, ADD COLUMN IF NOT EXISTS erro VARCHAR(255);
ALTER TABLE logs_autenticacao DROP CONSTRAINT IF EXISTS ck_logs_fator;
ALTER TABLE logs_autenticacao ADD CONSTRAINT ck_logs_fator CHECK (fator_2fa IN ('nome_materno','data_nascimento','cep','totp'));
ALTER TABLE profissionais ADD COLUMN IF NOT EXISTS id_filial INTEGER;
ALTER TABLE agendamentos ADD COLUMN IF NOT EXISTS id_filial INTEGER;
INSERT INTO filiais (id_estabelecimento, nome, status, ordem)
SELECT e.id_estabelecimento, 'Matriz', 'ativo', 0 FROM estabelecimento e
WHERE NOT EXISTS (SELECT 1 FROM filiais f WHERE f.id_estabelecimento = e.id_estabelecimento);
UPDATE profissionais p SET id_filial = (SELECT f.id_filial FROM filiais f WHERE f.id_estabelecimento=p.id_estabelecimento ORDER BY ordem, id_filial LIMIT 1) WHERE id_filial IS NULL;
UPDATE agendamentos a SET id_filial = (SELECT f.id_filial FROM filiais f WHERE f.id_estabelecimento=a.id_estabelecimento ORDER BY ordem, id_filial LIMIT 1) WHERE id_filial IS NULL;

DO $migration$
DECLARE r record; tabela text; tipo_perfil text;
BEGIN
  IF EXISTS (SELECT 1 FROM usuarios GROUP BY lower(email) HAVING count(*)>1) THEN
    RAISE EXCEPTION 'Emails duplicados: migracao interrompida sem excluir contas';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='usuarios'::regclass AND conname='uk_usuarios_email') THEN
    ALTER TABLE usuarios ADD CONSTRAINT uk_usuarios_email UNIQUE (email);
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='usuarios' AND column_name='id_estabelecimento') THEN
    INSERT INTO vinculos (id_estabelecimento, id_usuario, tipo, status, login, ultimo_acesso, data_criacao)
    SELECT id_estabelecimento, id_usuario, tipo, status, login, ultimo_acesso, data_criacao FROM usuarios
    ON CONFLICT (id_estabelecimento,id_usuario,tipo) DO NOTHING;
  END IF;
  FOR tabela, tipo_perfil IN VALUES ('clientes','cliente'),('profissionais','profissional'),('administradores','admin') LOOP
    EXECUTE format('INSERT INTO vinculos (id_estabelecimento,id_usuario,tipo,status) SELECT p.id_estabelecimento,p.id_usuario,%L,u.status FROM %I p JOIN usuarios u USING (id_usuario) ON CONFLICT (id_estabelecimento,id_usuario,tipo) DO NOTHING', tipo_perfil,tabela);
    EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS id_vinculo INTEGER',tabela);
    EXECUTE format('UPDATE %I p SET id_vinculo=v.id_vinculo FROM vinculos v WHERE p.id_vinculo IS NULL AND v.id_estabelecimento=p.id_estabelecimento AND v.id_usuario=p.id_usuario AND v.tipo=%L',tabela,tipo_perfil);
    EXECUTE format('ALTER TABLE %I ALTER COLUMN id_vinculo SET NOT NULL',tabela);
    FOR r IN SELECT conname FROM pg_constraint WHERE conrelid=tabela::regclass AND contype='f' AND confrelid='usuarios'::regclass AND cardinality(conkey)=2 LOOP
      EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I',tabela,r.conname);
    END LOOP;
    FOR r IN SELECT c.conname FROM pg_constraint c JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=c.conkey[1]
      WHERE c.conrelid=tabela::regclass AND c.contype='u' AND cardinality(c.conkey)=1 AND a.attname='id_usuario' LOOP
      EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I',tabela,r.conname);
    END LOOP;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid=tabela::regclass AND conname='uk_'||tabela||'_vinculo') THEN
      EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I UNIQUE (id_vinculo)',tabela,'uk_'||tabela||'_vinculo');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid=tabela::regclass AND conname='fk_tenant_'||tabela||'_id_vinculo') THEN
      EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY (id_estabelecimento,id_vinculo) REFERENCES vinculos(id_estabelecimento,id_vinculo) ON DELETE CASCADE ON UPDATE CASCADE',tabela,'fk_tenant_'||tabela||'_id_vinculo');
    END IF;
  END LOOP;
  FOR r IN SELECT conname FROM pg_constraint WHERE conrelid='notificacoes'::regclass AND contype='f' AND confrelid='usuarios'::regclass AND cardinality(conkey)=2 LOOP
    EXECUTE format('ALTER TABLE notificacoes DROP CONSTRAINT %I',r.conname);
  END LOOP;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='notificacoes'::regclass AND conname='fk_notificacao_usuario') THEN
    ALTER TABLE notificacoes ADD CONSTRAINT fk_notificacao_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE;
  END IF;
  -- As quatro colunas foram copiadas para vinculos antes de sua retirada.
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='usuarios' AND column_name='id_estabelecimento') THEN
    IF EXISTS (SELECT 1 FROM usuarios u WHERE NOT EXISTS (SELECT 1 FROM vinculos v WHERE v.id_usuario=u.id_usuario AND v.id_estabelecimento=u.id_estabelecimento AND v.tipo=u.tipo AND v.login IS NOT DISTINCT FROM u.login AND v.ultimo_acesso IS NOT DISTINCT FROM u.ultimo_acesso)) THEN
      RAISE EXCEPTION 'Vinculos incompletos: dados originais preservados por rollback';
    END IF;
    ALTER TABLE usuarios DROP COLUMN id_estabelecimento, DROP COLUMN tipo, DROP COLUMN login, DROP COLUMN ultimo_acesso;
  END IF;
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='vinculos'::regclass AND conname='uk_vinculos_login') THEN
    ALTER TABLE vinculos RENAME CONSTRAINT uk_vinculos_login TO uk_estabelecimento_login;
  END IF;
  FOREACH tabela IN ARRAY ARRAY['profissionais','agendamentos'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid=tabela::regclass AND conname='fk_'||tabela||'_filial') THEN
      EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY (id_filial) REFERENCES filiais(id_filial)',tabela,'fk_'||tabela||'_filial');
    END IF;
  END LOOP;
END
$migration$;
CREATE INDEX IF NOT EXISTS idx_vinculos_usuario ON vinculos (id_usuario);
CREATE INDEX IF NOT EXISTS idx_vinculos_tipo_status ON vinculos (id_estabelecimento, tipo, status);
CREATE INDEX IF NOT EXISTS idx_clientes_estabelecimento ON clientes (id_estabelecimento);
CREATE INDEX IF NOT EXISTS idx_clientes_tenant_usuario ON clientes (id_estabelecimento, id_usuario);
CREATE INDEX IF NOT EXISTS idx_clientes_tenant_vinculo ON clientes (id_estabelecimento, id_vinculo);
CREATE INDEX IF NOT EXISTS idx_profissionais_estabelecimento ON profissionais (id_estabelecimento);
CREATE INDEX IF NOT EXISTS idx_profissionais_tenant_usuario ON profissionais (id_estabelecimento, id_usuario);
CREATE INDEX IF NOT EXISTS idx_profissionais_tenant_vinculo ON profissionais (id_estabelecimento, id_vinculo);
CREATE INDEX IF NOT EXISTS idx_administradores_estabelecimento ON administradores (id_estabelecimento);
CREATE INDEX IF NOT EXISTS idx_administradores_tenant_usuario ON administradores (id_estabelecimento, id_usuario);
CREATE INDEX IF NOT EXISTS idx_administradores_tenant_vinculo ON administradores (id_estabelecimento, id_vinculo);
CREATE INDEX IF NOT EXISTS idx_servicos_status ON servicos (status);
CREATE INDEX IF NOT EXISTS idx_servicos_estabelecimento ON servicos (id_estabelecimento);
CREATE INDEX IF NOT EXISTS idx_ps_servico ON profissional_servico (id_servico);
CREATE INDEX IF NOT EXISTS idx_ps_estabelecimento ON profissional_servico (id_estabelecimento);
CREATE INDEX IF NOT EXISTS idx_ps_tenant_profissional ON profissional_servico (id_estabelecimento, id_profissional);
CREATE INDEX IF NOT EXISTS idx_ps_tenant_servico ON profissional_servico (id_estabelecimento, id_servico);
CREATE INDEX IF NOT EXISTS idx_horario_prof_dia ON horarios_profissionais (id_profissional, dia_semana, status);
CREATE INDEX IF NOT EXISTS idx_horarios_estabelecimento ON horarios_profissionais (id_estabelecimento);
CREATE INDEX IF NOT EXISTS idx_horarios_tenant_profissional ON horarios_profissionais (id_estabelecimento, id_profissional);
CREATE INDEX IF NOT EXISTS idx_bloqueio_prof_data ON bloqueios_agenda (id_profissional, data_bloqueio);
CREATE INDEX IF NOT EXISTS idx_bloqueios_usuario_criou ON bloqueios_agenda (id_usuario_criou);
CREATE INDEX IF NOT EXISTS idx_bloqueios_estabelecimento ON bloqueios_agenda (id_estabelecimento);
CREATE INDEX IF NOT EXISTS idx_bloqueios_tenant_profissional ON bloqueios_agenda (id_estabelecimento, id_profissional);
CREATE INDEX IF NOT EXISTS idx_agend_profissional_data ON agendamentos (id_profissional, data_agendamento, hora_inicio);
CREATE INDEX IF NOT EXISTS idx_agend_cliente_data ON agendamentos (id_cliente, data_agendamento);
CREATE INDEX IF NOT EXISTS idx_agend_status_data ON agendamentos (status, data_agendamento);
CREATE INDEX IF NOT EXISTS idx_agend_servico ON agendamentos (id_servico);
CREATE INDEX IF NOT EXISTS idx_agend_usuario_cancelou ON agendamentos (id_usuario_cancelou);
CREATE INDEX IF NOT EXISTS idx_agendamentos_estabelecimento ON agendamentos (id_estabelecimento);
CREATE INDEX IF NOT EXISTS idx_agend_tenant_cliente ON agendamentos (id_estabelecimento, id_cliente);
CREATE INDEX IF NOT EXISTS idx_agend_tenant_profissional ON agendamentos (id_estabelecimento, id_profissional);
CREATE INDEX IF NOT EXISTS idx_agend_tenant_servico ON agendamentos (id_estabelecimento, id_servico);
CREATE INDEX IF NOT EXISTS idx_lista_vaga ON lista_espera (id_estabelecimento, data_desejada, id_profissional, status);
CREATE INDEX IF NOT EXISTS idx_notificacao_fila ON notificacoes (id_estabelecimento, status, data_programada);
CREATE INDEX IF NOT EXISTS idx_pagamento_status ON pagamentos (id_estabelecimento, status);
CREATE INDEX IF NOT EXISTS idx_fidelidade_cliente ON fidelidade_movimentos (id_estabelecimento, id_cliente);
CREATE INDEX IF NOT EXISTS idx_pacote_status ON pacotes (id_estabelecimento, status);
CREATE INDEX IF NOT EXISTS idx_cliente_pacotes ON cliente_pacotes (id_estabelecimento, id_cliente, status_pagamento);
CREATE INDEX IF NOT EXISTS idx_avaliacao_profissional ON avaliacoes (id_estabelecimento, id_profissional, status);
CREATE INDEX IF NOT EXISTS idx_logs_estabelecimento ON logs_autenticacao (id_estabelecimento, data_hora);
CREATE INDEX IF NOT EXISTS idx_logs_nome ON logs_autenticacao (nome);
CREATE INDEX IF NOT EXISTS idx_logs_cpf ON logs_autenticacao (cpf);
CREATE INDEX IF NOT EXISTS idx_ep_plano ON estabelecimento_plano (id_plano);
CREATE INDEX IF NOT EXISTS idx_logs_master_data ON logs_master (data_hora);
CREATE INDEX IF NOT EXISTS idx_logs_master_acao ON logs_master (acao);
CREATE INDEX IF NOT EXISTS idx_logs_master_empresa ON logs_master (id_estabelecimento, data_hora);
CREATE INDEX IF NOT EXISTS idx_tentativa_busca ON tentativas_acesso (escopo, chave, data_hora);
CREATE INDEX IF NOT EXISTS idx_configuracoes_estabelecimento ON configuracoes (id_estabelecimento);
CREATE INDEX IF NOT EXISTS idx_filiais_estabelecimento ON filiais (id_estabelecimento, status);
CREATE INDEX IF NOT EXISTS idx_profissionais_filial ON profissionais (id_estabelecimento, id_filial);
CREATE INDEX IF NOT EXISTS idx_agendamentos_filial ON agendamentos (id_estabelecimento, id_filial);
CREATE INDEX IF NOT EXISTS idx_sessoes_lembradas_usuario ON sessoes_lembradas (id_estabelecimento, id_usuario);
CREATE INDEX IF NOT EXISTS idx_sessoes_lembradas_vinculo ON sessoes_lembradas (id_vinculo);
CREATE INDEX IF NOT EXISTS idx_sessoes_lembradas_expira ON sessoes_lembradas (expira_em);
