"""Desenvolve as explicações das atividades registradas, sem criar novas atas."""
RELATOS = {
    '15/08/2026': [
        'O planejamento inicial concentrou a proposta do Agendei na organização de serviços e horários de atendimento. A divisão entre Front-end e Back-end permitiu distribuir o trabalho de acordo com as necessidades do projeto: de um lado, a construção das telas e da navegação; de outro, a preparação das regras, das operações e da persistência dos dados. Essa organização fornece uma referência para acompanhar a participação de cada integrante ao longo do desenvolvimento.',
        'A relação entre essas duas frentes é essencial para o sistema. As telas precisam apresentar informações claras sobre serviços, profissionais e reservas, enquanto o servidor deve conferir os dados recebidos e aplicar as regras de disponibilidade. O levantamento dos objetivos, portanto, orienta tanto a experiência do cliente quanto o controle administrativo do estabelecimento, evitando que o desenvolvimento fique limitado à aparência das páginas.',
    ],
    '22/08/2026': [
        'A estrutura inicial do Back-end constitui a base para separar o acesso aos dados das operações utilizadas nas telas. O planejamento das rotas e a definição das regras de negócio ajudam a organizar como as informações de serviços, profissionais e agendamentos serão solicitadas e processadas. Esse trabalho também permite identificar quais operações dependem de autenticação e quais informações precisam ser relacionadas ao estabelecimento correto.',
        'No Front-end, a criação das primeiras telas e a organização da navegação dão forma ao percurso do usuário. A sequência entre entrada, cadastro e acesso às funcionalidades precisa ser compreensível para que o cliente encontre o que procura. O andamento registrado para essa etapa combina, assim, a preparação da estrutura interna com a construção da interface que será utilizada para interagir com ela.',
    ],
    '27/08/2026': [
        'A elaboração do relatório e da análise de requisitos aproxima a proposta acadêmica do comportamento esperado da aplicação. A descrição das funcionalidades explicita o que cada perfil poderá fazer, enquanto os requisitos não funcionais orientam aspectos como organização do código, segurança, responsividade e facilidade de utilização. O documento também serve como referência comum para relacionar as tarefas distribuídas entre os integrantes.',
        'A discussão da proposta permite apresentar o Agendei como uma solução para situações concretas: consultar horários livres, registrar reservas e acompanhar atendimentos. A distribuição de responsabilidades e a formalização mencionadas no relato fazem parte da organização do trabalho coletivo. O propósito dessa etapa é manter alinhados o desenvolvimento das páginas, a aplicação das regras de negócio e a documentação que acompanha a entrega.',
    ],
    '29/08/2026': [
        'O gerenciamento dos dados e o desenvolvimento das operações de agendamento envolvem a relação entre cliente, profissional, serviço e horário. Uma reserva precisa carregar essas informações de maneira consistente, pois delas dependem a consulta da agenda, a duração do atendimento e a identificação dos registros de cada estabelecimento. As validações citadas no relato apoiam esse processo, conferindo os dados antes que uma operação seja aceita.',
        'As telas de cadastro e os componentes visuais fazem a ligação entre essas regras e o preenchimento realizado pelo usuário. Campos organizados, rótulos identificáveis e mensagens de orientação ajudam a reduzir erros e tornam os formulários mais compreensíveis. Nessa fase, o trabalho das duas áreas se complementa: o Front-end recebe e apresenta os dados, e o Back-end mantém a responsabilidade pela validação definitiva e pelo armazenamento.',
    ],
    '03/09/2026': [
        'A apresentação da versão inicial oferece uma visão conjunta dos módulos que compõem a aplicação. Ao relacionar cadastro, login, permissões e agendamento, a documentação deixa mais claro que o sistema não se resume à escolha de um horário. Cada etapa depende da identificação do usuário, do perfil autorizado e das informações cadastradas pelo estabelecimento, formando um fluxo que precisa funcionar de maneira integrada.',
        'A análise das áreas de cliente, profissional e administrador também destaca a necessidade de apresentar informações diferentes para cada público. O cliente acompanha suas reservas, o profissional consulta a própria agenda e o administrador organiza a operação da empresa. A revisão das telas e dos testes, citada como próximo passo no registro, utiliza essa separação como referência para conferir a navegação e as regras de acesso.',
    ],
    '05/09/2026': [
        'A integração com o banco de dados conecta as operações da aplicação aos registros que precisam permanecer disponíveis após o encerramento da sessão. Alterações e cancelamentos de reservas exigem atenção ao estado do agendamento, à identificação de quem realiza a ação e ao efeito da operação na disponibilidade. A revisão das regras de conflito é parte desse cuidado, pois o intervalo de um atendimento precisa ser considerado em sua duração completa.',
        'Os ajustes de layout e a comunicação com a API contribuem para apresentar essas informações de forma coerente nas telas. A interface deve carregar os profissionais e os horários compatíveis com a escolha do serviço, sem oferecer opções que contradigam as regras do servidor. O trabalho registrado nesta etapa aproxima a estrutura dos dados do fluxo visível para o usuário, preparando as funcionalidades para uma utilização conjunta.',
    ],
    '12/09/2026': [
        'A revisão da estrutura do servidor, das rotas e das regras de negócio tem como foco a consistência entre as operações disponíveis. A criação de uma reserva, por exemplo, precisa respeitar expediente, bloqueios, antecedência e associação entre profissional e serviço. O teste dessas rotas ajuda a verificar se as respostas obtidas pela interface correspondem ao comportamento esperado e se as situações inválidas recebem tratamento adequado.',
        'A correção de detalhes visuais e a verificação dos formulários complementam essa revisão. Além de organizar a apresentação dos campos, é necessário que as mensagens orientem o preenchimento e que a navegação mantenha uma sequência compreensível. A atenção aos formulários é relevante porque boa parte das informações utilizadas no sistema começa no cadastro e nas escolhas realizadas pelo próprio usuário.',
    ],
    '19/09/2026': [
        'Os ajustes nos serviços do Back-end e a revisão dos endpoints concentram a atenção na comunicação entre os módulos. Uma resposta precisa informar à interface se a operação foi aceita, se os dados devem ser corrigidos ou se ocorreu uma indisponibilidade. O tratamento de erros citado no registro é importante para que essas situações sejam apresentadas de maneira compreensível e para evitar que uma falha interrompa a navegação sem orientação.',
        'O aprimoramento das telas e da integração com a API acompanha esse trabalho, pois os estados da aplicação precisam aparecer de forma clara para o usuário. Listagens, formulários e mensagens dependem dos dados retornados pelo servidor. Essa etapa reúne, portanto, a revisão das operações internas e o cuidado com a forma como seus resultados são exibidos, contribuindo para uma utilização mais consistente do sistema.',
    ],
    '26/09/2026': [
        'Os testes do servidor, do acesso aos dados e das operações de agendamento relacionam os componentes que foram desenvolvidos nas etapas anteriores. O foco deixa de ser somente uma função isolada e passa a abranger a interação entre consulta, validação e gravação. A verificação das regras de preenchimento também ajuda a conferir se dados incompletos ou incompatíveis são tratados antes de gerar registros inconsistentes.',
        'As correções visuais e os ajustes dos componentes do Front-end acompanham essa integração. A organização de botões, campos e informações precisa facilitar a execução das tarefas de cada perfil, especialmente nos fluxos de cadastro e reserva. As atividades registradas para o período demonstram a distribuição do trabalho de revisão entre os integrantes, mantendo a atenção tanto no funcionamento quanto na apresentação da aplicação.',
    ],
    '03/10/2026': [
        'A revisão final do Back-end e das funcionalidades de agendamento reúne os pontos centrais da operação do Agendei: identificação dos usuários, aplicação das regras de disponibilidade e acompanhamento das reservas. Os testes complementares citados no relato apoiam a conferência das validações e do tratamento de situações que exigem uma resposta específica do servidor. Essas atividades fazem parte da preparação do projeto para apresentação e avaliação.',
        'A finalização do layout e a revisão da navegação procuram manter consistência entre as telas e a integração com a API. O objetivo dessa etapa é apresentar uma sequência compreensível de utilização, com informações e mensagens compatíveis com as operações disponíveis. O conjunto das contribuições registradas encerra o acompanhamento das tarefas descritas nas reuniões, articulando a parte técnica, a interface e a organização da entrega acadêmica.',
    ],
}
