<?php

/**
 * Migracao aditiva: filiais (unidades) do estabelecimento.
 *
 * Cria a tabela filiais, acrescenta id_filial em profissionais e agendamentos,
 * cria uma filial "Matriz" para cada estabelecimento que ainda nao tem nenhuma
 * e move para ela tudo o que ja existia. Pode rodar de novo sem efeito colateral.
 * Atende MySQL/MariaDB e PostgreSQL. Execute: php scripts/migrar_filiais.php
 */
if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

require_once __DIR__ . '/../config/database.php';

$db         = bd();
$ehPostgres = Database::ehPostgres();

// O information_schema existe nos dois dialetos; muda so o nome do esquema atual.
$esquemaAtual = $ehPostgres ? 'current_schema()' : 'DATABASE()';

$colunaExiste = static function (string $tabela, string $coluna) use ($db, $esquemaAtual): bool {
    $q = $db->prepare(
        "SELECT 1 FROM information_schema.columns
         WHERE table_schema = $esquemaAtual AND table_name = ? AND column_name = ?"
    );
    $q->execute([$tabela, $coluna]);

    return (bool) $q->fetchColumn();
};

$constraintExiste = static function (string $tabela, string $nome) use ($db, $esquemaAtual): bool {
    $q = $db->prepare(
        "SELECT 1 FROM information_schema.table_constraints
         WHERE table_schema = $esquemaAtual AND table_name = ? AND constraint_name = ?"
    );
    $q->execute([$tabela, $nome]);

    return (bool) $q->fetchColumn();
};

// ---------------------------------------------------------------------
// 1. Tabela filiais
// A foto vai em base64 (data URI). No MySQL o TEXT tem 64 KB, insuficiente para
// uma imagem de 512 KB codificada; por isso MEDIUMTEXT, como o logo ja usa.
// ---------------------------------------------------------------------
if ($ehPostgres) {
    $db->exec("CREATE TABLE IF NOT EXISTS filiais (
        id_filial          INTEGER GENERATED BY DEFAULT AS IDENTITY,
        id_estabelecimento INTEGER NOT NULL,
        nome               VARCHAR(120) NOT NULL,
        telefone           VARCHAR(20) DEFAULT NULL,
        cep                CHAR(8) DEFAULT NULL,
        logradouro         VARCHAR(150) DEFAULT NULL,
        numero             VARCHAR(20) DEFAULT NULL,
        complemento        VARCHAR(60) DEFAULT NULL,
        bairro             VARCHAR(100) DEFAULT NULL,
        cidade             VARCHAR(100) DEFAULT NULL,
        uf                 CHAR(2) DEFAULT NULL,
        foto               TEXT DEFAULT NULL,
        status             VARCHAR(7) NOT NULL DEFAULT 'ativo',
        ordem              SMALLINT NOT NULL DEFAULT 0,
        data_cadastro      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT pk_filiais PRIMARY KEY (id_filial),
        CONSTRAINT uk_filiais_registro UNIQUE (id_estabelecimento, id_filial),
        CONSTRAINT ck_filiais_status CHECK (status IN ('ativo','inativo')),
        CONSTRAINT fk_filiais_estabelecimento FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento)
    )");
    $db->exec('CREATE INDEX IF NOT EXISTS idx_filiais_estabelecimento ON filiais (id_estabelecimento, status)');
} else {
    $db->exec("CREATE TABLE IF NOT EXISTS filiais (
        id_filial          int(10) unsigned NOT NULL AUTO_INCREMENT,
        id_estabelecimento int(10) unsigned NOT NULL,
        nome               varchar(120) NOT NULL,
        telefone           varchar(20) DEFAULT NULL,
        cep                char(8) DEFAULT NULL,
        logradouro         varchar(150) DEFAULT NULL,
        numero             varchar(20) DEFAULT NULL,
        complemento        varchar(60) DEFAULT NULL,
        bairro             varchar(100) DEFAULT NULL,
        cidade             varchar(100) DEFAULT NULL,
        uf                 char(2) DEFAULT NULL,
        foto               mediumtext DEFAULT NULL,
        status             enum('ativo','inativo') NOT NULL DEFAULT 'ativo',
        ordem              smallint(5) NOT NULL DEFAULT 0,
        data_cadastro      datetime NOT NULL DEFAULT current_timestamp(),
        PRIMARY KEY (id_filial),
        UNIQUE KEY uk_filiais_registro (id_estabelecimento, id_filial),
        KEY idx_filiais_estabelecimento (id_estabelecimento, status),
        CONSTRAINT fk_filiais_estabelecimento FOREIGN KEY (id_estabelecimento) REFERENCES estabelecimento (id_estabelecimento)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
}
echo "Tabela filiais pronta.\n";

// ---------------------------------------------------------------------
// 2. Coluna id_filial em profissionais e agendamentos (nula por enquanto:
//    o preenchimento vem no passo 3, e a aplicacao sempre grava o valor).
// ---------------------------------------------------------------------
foreach (['profissionais', 'agendamentos'] as $tabela) {
    if (!$colunaExiste($tabela, 'id_filial')) {
        $db->exec($ehPostgres
            ? "ALTER TABLE $tabela ADD COLUMN id_filial INTEGER DEFAULT NULL"
            : "ALTER TABLE $tabela ADD COLUMN id_filial int(10) unsigned DEFAULT NULL");
        echo "Coluna id_filial adicionada em $tabela.\n";
    }
}

// ---------------------------------------------------------------------
// 3. Matriz para quem nao tem filial, e tudo o que existia vai para ela.
// ---------------------------------------------------------------------
$buscaMatriz = $db->prepare(
    'SELECT id_filial FROM filiais WHERE id_estabelecimento = ? ORDER BY ordem ASC, id_filial ASC LIMIT 1'
);
$criaMatriz = $db->prepare(
    "INSERT INTO filiais (id_estabelecimento, nome, status, ordem) VALUES (?, 'Matriz', 'ativo', 0)"
);
$moveProfissionais = $db->prepare(
    'UPDATE profissionais SET id_filial = ? WHERE id_estabelecimento = ? AND id_filial IS NULL'
);
$moveAgendamentos = $db->prepare(
    'UPDATE agendamentos SET id_filial = ? WHERE id_estabelecimento = ? AND id_filial IS NULL'
);

foreach ($db->query('SELECT id_estabelecimento FROM estabelecimento')->fetchAll() as $linha) {
    $idEstabelecimento = (int) $linha['id_estabelecimento'];

    $buscaMatriz->execute([$idEstabelecimento]);
    $idFilial = (int) $buscaMatriz->fetchColumn();

    if ($idFilial <= 0) {
        $criaMatriz->execute([$idEstabelecimento]);
        $idFilial = (int) $db->lastInsertId();
        echo "Filial Matriz criada para o estabelecimento $idEstabelecimento.\n";
    }

    $moveProfissionais->execute([$idFilial, $idEstabelecimento]);
    $moveAgendamentos->execute([$idFilial, $idEstabelecimento]);
}

// ---------------------------------------------------------------------
// 4. Chaves estrangeiras e indices, so depois de tudo preenchido.
// ---------------------------------------------------------------------
$vinculos = [
    ['profissionais', 'fk_profissionais_filial', 'idx_profissionais_filial'],
    ['agendamentos',  'fk_agendamentos_filial',  'idx_agendamentos_filial'],
];

foreach ($vinculos as [$tabela, $fk, $indice]) {
    if (!$constraintExiste($tabela, $fk)) {
        $db->exec("ALTER TABLE $tabela ADD CONSTRAINT $fk FOREIGN KEY (id_filial) REFERENCES filiais (id_filial)");
        echo "Chave $fk criada.\n";
    }
    $db->exec($ehPostgres
        ? "CREATE INDEX IF NOT EXISTS $indice ON $tabela (id_estabelecimento, id_filial)"
        : "CREATE INDEX IF NOT EXISTS $indice ON $tabela (id_estabelecimento, id_filial)");
}

$dialeto = $ehPostgres ? 'PostgreSQL' : 'MySQL/MariaDB';
echo "Filiais migradas em $dialeto: profissionais e agendamentos vinculados a uma unidade.\n";
