<?php

/**
 * Migracao aditiva: "manter conectado" (dispositivos lembrados).
 *
 * Cria a tabela sessoes_lembradas, onde fica o hash do segredo do cookie de
 * "manter conectado" (models/SessaoLembrada.php). Pode rodar de novo sem
 * efeito colateral. Atende MySQL/MariaDB e PostgreSQL (Supabase).
 * Execute: php scripts/migrar_lembrar.php
 */
if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

require_once __DIR__ . '/../config/database.php';

$db         = bd();
$ehPostgres = Database::ehPostgres();

$esquemaAtual = $ehPostgres ? 'current_schema()' : 'DATABASE()';
$q = $db->prepare("SELECT 1 FROM information_schema.tables WHERE table_schema = $esquemaAtual AND table_name = 'sessoes_lembradas'");
$q->execute();
$existia = (bool) $q->fetchColumn();

if ($ehPostgres) {
    $db->exec("CREATE TABLE IF NOT EXISTS sessoes_lembradas (
        id_sessao          INTEGER GENERATED BY DEFAULT AS IDENTITY,
        id_estabelecimento INTEGER NOT NULL,
        id_usuario         INTEGER NOT NULL,
        seletor            CHAR(24) NOT NULL,
        validador_hash     CHAR(64) NOT NULL,
        expira_em          TIMESTAMP NOT NULL,
        criado_em          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        ultimo_uso         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT pk_sessoes_lembradas PRIMARY KEY (id_sessao),
        CONSTRAINT uk_sessoes_lembradas_seletor UNIQUE (seletor),
        CONSTRAINT fk_sessoes_lembradas_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario) ON DELETE CASCADE
    )");
    $db->exec('CREATE INDEX IF NOT EXISTS idx_sessoes_lembradas_usuario ON sessoes_lembradas (id_estabelecimento, id_usuario)');
    $db->exec('CREATE INDEX IF NOT EXISTS idx_sessoes_lembradas_expira ON sessoes_lembradas (expira_em)');
} else {
    $db->exec("CREATE TABLE IF NOT EXISTS sessoes_lembradas (
        id_sessao          int(10) unsigned NOT NULL AUTO_INCREMENT,
        id_estabelecimento int(10) unsigned NOT NULL,
        id_usuario         int(10) unsigned NOT NULL,
        seletor            char(24) NOT NULL,
        validador_hash     char(64) NOT NULL,
        expira_em          datetime NOT NULL,
        criado_em          datetime NOT NULL DEFAULT current_timestamp(),
        ultimo_uso         datetime NOT NULL DEFAULT current_timestamp(),
        PRIMARY KEY (id_sessao),
        UNIQUE KEY uk_sessoes_lembradas_seletor (seletor),
        KEY idx_sessoes_lembradas_usuario (id_estabelecimento, id_usuario),
        KEY idx_sessoes_lembradas_expira (expira_em),
        CONSTRAINT fk_sessoes_lembradas_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
}

// Confere que a tabela responde de verdade, e nao apenas que o CREATE passou.
$db->query('SELECT id_sessao, seletor, validador_hash, expira_em FROM sessoes_lembradas LIMIT 1')->fetch();

echo $existia
    ? "Manter conectado: a tabela sessoes_lembradas ja existia.\n"
    : "Manter conectado: tabela sessoes_lembradas criada.\n";
